server:
  port: ${server.port}
  context-path: ${server.contextPath}
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml

spring:
  datasource:
      url: ${jdbc.url}
      driver-class-name: ${jdbc.driverName}
      username: ${jdbc.username}
      password: ${jdbc.password}
